<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Statemachine" nsURI="www.Statemachine.com" nsPrefix="Statemachine">
  <eClassifiers xsi:type="ecore:EClass" name="JointState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="successors" upperBound="-1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reachable" upperBound="-1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="Jonction" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForkandJointState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="NormalState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//Declaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="machineVariables" upperBound="-1"
        eType="#//StateMachineVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachineVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionStatement" eType="#//Statement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guardExpression" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement">
    <eAnnotations/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionStatement" eType="#//Statement"/>
  </eClassifiers>
</ecore:EPackage>
